// Binary plist encoding/decoding and RTI text input payload tests.
// Reference bytes are generated by Python plistlib (matching pyatv) to verify decoding
// correctness; the encoding side is validated by round-tripping through decoding.

import Foundation
import AppleTVControl

func runBinaryPlistTests() {
    runSuite("BinaryPlist decode _tiD") {
        // _tiD generated by fake_device.rti_encoded_data (sessionUUID=0x00..0x0F, text="hello").
        let tiData = Data(hex: "62706c6973743030d2010203085424746f7058246f626a65637473d2040506075b73657373696f6e555549445d646f63756d656e74537461746580018002a5090a0b0e1155246e756c6c4f1010000102030405060708090a0b0c0d0e0fd10c0d55646f6353748003d10f105f1012636f6e746578744265666f7265496e70757480045568656c6c6f080d121b202c3a3c3e444a5d6066686b80820000000000000101000000000000001200000000000000000000000000000088")!

        let props = RTITextInput.readArchiveProperties(tiData, paths: [
            ["sessionUUID"],
            ["documentState", "docSt", "contextBeforeInput"],
        ])

        let expectedUUID = Data((0..<16).map { UInt8($0) })
        expectEqual(props.count, 2, "parsed path count")
        expectEqual(props[0] as? Data, expectedUUID, "sessionUUID")
        expectEqual(props[1] as? String, "hello", "current text")
    }

    runSuite("RTI input payload round-trip") {
        let uuid = Data((0..<16).map { UInt8($0) })
        let payload = RTITextInput.inputTextPayload(sessionUUID: uuid, text: "café")

        let props = RTITextInput.readArchiveProperties(payload, paths: [
            ["textOperations", "targetSessionUUID", "NS.uuidbytes"],
            ["textOperations", "keyboardOutput", "insertionText"],
        ])

        expectEqual(props[0] as? Data, uuid, "sessionUUID")
        expectEqual(props[1] as? String, "café", "inserted text (non-ASCII)")
    }

    runSuite("RTI clear payload round-trip") {
        let uuid = Data((0..<16).map { UInt8($0) })
        let payload = RTITextInput.clearTextPayload(sessionUUID: uuid)

        let props = RTITextInput.readArchiveProperties(payload, paths: [
            ["textOperations", "targetSessionUUID", "NS.uuidbytes"],
            ["textOperations", "textToAssert"],
        ])

        expectEqual(props[0] as? Data, uuid, "sessionUUID")
        expectEqual(props[1] as? String, "", "textToAssert is empty")
    }
}
